---
- name: Install mysql/mariadb connector packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-connector-java
    - MySQL-python
- name: Install Hive
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - hive
    - hive-server2
    - hive-hcatalog
    - hive-hcatalog-server
    - hive-webhcat
    - hive-webhcat-server
- name: Copy hive-site.xml
  template:
    owner: root
    group: root
    mode: "644"
    src: hive-site.xml.j2
    dest: /etc/hive/conf/hive-site.xml
- name: Create Hive Metastore in database
  mysql_db:
    name: hive_metastore
    login_host: "{{ mariadb_server }}"
    login_user: root
    login_password: ""
    state: present
- name: Allow the hive user to access the Hive Metastore
  mysql_user:
    name: hive
    host: "%"
    password: password
    login_host: "{{ mariadb_server }}"
    login_user: root
    login_password: ""
    priv: hive_metastore.*:ALL
    state: present
- name: Symlink mysql-connector-java to Hive's lib directory
  file:
    name: /usr/lib/hive/lib/mysql-connector-java.jar
    state: link
    src: /usr/share/java/mysql-connector-java.jar
    owner: root
    group: root
