---
- name: Install Zookeeper
  yum:
    name: zookeeper,zookeeper-server
    state: present
- name: Setup myid
  template:
    owner: zookeeper
    group: zookeeper
    mode: "600"
    src: myid.j2
    dest: /var/lib/zookeeper/myid
- name: Setup zoo.cfg
  template:
    owner: root
    group: root
    mode: "644"
    src: zoo.cfg.j2
    dest: /etc/zookeeper/conf/zoo.cfg
- name: Setup zkEnv.sh
  copy:
    owner: root
    group: root
    mode: "755"
    src: zkEnv.sh
    dest: /usr/lib/zookeeper/bin/zkEnv.sh
