---
- name: Install Zookeeper
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - zookeeper
    - zookeeper-server
- name: Disable Zookeeper
  service:
    name: zookeeper-server
    enabled: no
- name: Setup default files
  copy:
    owner: root
    group: root
    mode: "644"
    src: default/
    dest: /etc/default
- name: Setup myid
  template:
    owner: zookeeper
    group: zookeeper
    mode: "600"
    src: myid.j2
    dest: /var/lib/zookeeper/myid
- name: Setup zoo.cfg
  template:
    owner: root
    group: root
    mode: "644"
    src: zoo.cfg.j2
    dest: /etc/zookeeper/conf/zoo.cfg
