---
- name: Copy Zookeeper RPM
  copy:
    owner=root
    group=root
    mode=600
    src=zookeeper-3.4.6-1.fc21.noarch.rpm
    dest=/tmp/zookeeper-3.4.6-1.fc21.noarch.rpm
- name: Install Zookeeper
  yum:
    name=/tmp/zookeeper-3.4.6-1.fc21.noarch.rpm
    state=present
- name: Create /var/opt/zookeeper
  file:
    name=/var/opt/zookeeper
    owner=zookeeper
    group=zookeeper
    mode=700
    state=directory
- name: Setup myid
  template:
    owner=zookeeper
    group=zookeeper
    mode=600
    src=myid.j2
    dest=/var/opt/zookeeper/myid
- name: Create /opt/zookeeper/conf
  file:
    name=/opt/zookeeper/conf
    owner=root
    group=root
    mode=755
    state=directory
- name: Setup zoo.cfg
  template:
    owner=root
    group=root
    mode=644
    src=zoo.cfg.j2
    dest=/opt/zookeeper/conf/zoo.cfg
- name: Setup zkEnv.sh
  file:
    owner=root
    group=root
    mode=755
    src=zkEnv.sh
    dest=/opt/zookeeper/bin/zkEnv.sh
