---
- name: Install Hadoop
  yum:
    name: hadoop,hadoop-hdfs,hadoop-hdfs-datanode,hadoop-hdfs-namenode,hadoop-hdfs-secondarynamenode,hadoop-mapreduce,hadoop-yarn,hadoop-mapreduce-historyserver,hadoop-yarn-nodemanager,hadoop-yarn-resourcemanager
    state: present
- name: Setup static Hadoop config files
  copy:
    owner: root
    group: root
    mode: 644
    src: config/
    dest: /etc/hadoop/conf
- name: Setup templated Hadoop config files
  template:
    owner: root
    group: root
    mode: 644
    src: "{{ item }}.j2"
    dest: /etc/hadoop/conf/{{ item }}
  with_items:
    - core-site.xml
    - hdfs-site.xml
    - slaves
    - yarn-site.xml
    - mapred-site.xml
