---
- name: Install Hadoop
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - hadoop
    - hadoop-hdfs
    - hadoop-hdfs-datanode
    - hadoop-hdfs-namenode
    - hadoop-hdfs-secondarynamenode
    - hadoop-yarn
    - hadoop-yarn-nodemanager
    - hadoop-yarn-resourcemanager
    - hadoop-mapreduce
    - hadoop-mapreduce-historyserver
- name: Disable Hadoop
  service:
    name: "{{ item }}"
    enabled: no
  with_items:
    - hadoop-hdfs-namenode
    - hadoop-hdfs-datanode
    - hadoop-hdfs-secondarynamenode
    - hadoop-yarn-resourcemanager
    - hadoop-yarn-nodemanager
    - hadoop-mapreduce-historyserver
- name: Setup static config files
  copy:
    owner: root
    group: root
    mode: "644"
    src: config/
    dest: /etc/hadoop/conf
- name: Setup default files
  copy:
    owner: root
    group: root
    mode: "644"
    src: default/
    dest: /etc/default
- name: Setup templated config files
  template:
    owner: root
    group: root
    mode: "644"
    src: "{{ item }}.j2"
    dest: /etc/hadoop/conf/{{ item }}
  with_items:
    - core-site.xml
    - hdfs-site.xml
    - slaves
    - yarn-site.xml
    - mapred-site.xml
