---
- hosts: all
  remote_user: root
  roles:
    - hosts_file
    - base_packages
    - java
    - firewalld
    - journald
    - admin_user

- hosts: time_server
  remote_user: root
  roles:
    - chrony_server

- hosts: time_client
  remote_user: root
  roles:
    - chrony_client

- hosts: hadoop_namenode:hadoop_datanode
  remote_user: root
  roles:
    - hadoop

- hosts: zookeeper
  remote_user: root
  roles:
    - zookeeper

- hosts: hbase_master:hbase_regionserver
  remote_user: root
  roles:
    - hbase

- hosts: solr
  remote_user: root
  roles:
    - solr

- hosts: pig
  remote_user: root
  roles:
    - pig
