---
- hosts: all
  remote_user: vagrant
  sudo: yes
  roles:
    - base_packages
    - java
    - firewalld
    - journald
    - admin_user

- hosts: development
  remote_user: vagrant
  sudo: yes
  roles:
    - development

- hosts: time_server
  remote_user: vagrant
  sudo: yes
  roles:
    - chrony_server

- hosts: time_client
  remote_user: vagrant
  sudo: yes
  roles:
    - chrony_client

# It is important that this entry shows up before any others that expect
# a working SQL server.
# This "dependency" should not be handled via role dependencies since
# one server may expect MariaDB to be running on another server.
# Using a role dependency would force each machine to have its own
# MariaDB server.
- hosts: mariadb
  remote_user: vagrant
  sudo: yes
  roles:
    - mariadb

- hosts: hadoop_namenode:hadoop_datanode
  remote_user: vagrant
  sudo: yes
  roles:
    - hadoop

- hosts: zookeeper
  remote_user: vagrant
  sudo: yes
  roles:
    - zookeeper

- hosts: hbase_master:hbase_regionserver
  remote_user: vagrant
  sudo: yes
  roles:
    - hbase

- hosts: solr
  remote_user: vagrant
  sudo: yes
  roles:
    - solr

- hosts: pig
  remote_user: vagrant
  sudo: yes
  roles:
    - pig

- hosts: hive
  remote_user: vagrant
  sudo: yes
  roles:
    - hive

- hosts: sqoop
  remote_user: vagrant
  sudo: yes
  roles:
    - sqoop

- hosts: flume
  remote_user: vagrant
  sudo: yes
  roles:
    - flume
