---
- hosts: vm_grid_all
  remote_user: root
  roles:
    - hosts_file
    - base_packages
    - java
    - firewalld
    - journald
    - admin_user

- hosts: time_server
  remote_user: root
  roles:
    - chrony_server

- hosts: time_client
  remote_user: root
  roles:
    - chrony_client

- hosts: hadoop
  remote_user: root
  roles:
    - hadoop

- hosts: zookeeper
  remote_user: root
  roles:
    - zookeeper

- hosts: hbase
  remote_user: root
  roles:
    - hbase

- hosts: solr
  remote_user: root
  roles:
    - solr
