---
- name: Install Flume
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - flume
    - flume-agent
- name: Disable Flume
  service:
    name: flume-agent
    enabled: no
- name: Setup default files
  copy:
    owner: root
    group: root
    mode: "644"
    src: default/
    dest: /etc/default
