---
- name: Install MariaDB Client
  yum:
    name=mariadb
    state=present
- name: Install MariaDB Server
  yum:
    name=mariadb-server
    state=present
- name: Enable MariaDB
  service:
    name=mariadb
    enabled=yes
    state=started
# TODO: Automate mysql_secure_installation instead
- name: Delete anonymous users
  mysql_user:
    name=
    host={{ item }}
    login_user=root
    login_password=
    state=absent
  with_items:
    - localhost
    - "{{ inventory_hostname }}"
- name: Allow root login from all servers
  mysql_user:
    name=root
    host=%
    password=
    login_host={{ mariadb_server }}
    login_user=root
    login_password=
    priv=*.*:ALL
    state=present
