---
- name: Install MariaDB
  yum:
    name=mariadb
    state=present
- name: Enable MariaDB
  service:
    name=mariadb
    enabled=yes
    state=started
- name: Install MySQL-python
  yum:
    name=MySQL-python
    state=present
- name: Install mysql-connector-java
  yum:
    name=mysql-connector-java
    state=present
