---
- name: Install HBase
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - hbase
    - hbase-master
    - hbase-regionserver
- name: Disable HBase
  service:
    name: "{{ item }}"
    enabled: no
  with_items:
    - hbase-master
    - hbase-regionserver
- name: Copy hbase-env.sh
  copy:
    owner: root
    group: root
    mode: "755"
    src: hbase-env.sh
    dest: /etc/hbase/conf/hbase-env.sh
- name: Setup template files
  template:
    owner: root
    group: root
    mode: "644"
    src: "{{ item }}.j2"
    dest: /etc/hbase/conf/{{ item }}
  with_items:
    - hbase-site.xml
    - regionservers
