---
- name: Copy Solr RPM
  copy:
    owner=root
    group=root
    mode=600
    src=solr-5.0.0-1.fc21.noarch.rpm
    dest=/tmp/solr-5.0.0-1.fc21.noarch.rpm
- name: Install Solr
  yum:
    name=/tmp/solr-5.0.0-1.fc21.noarch.rpm
    state=present
