---
- name: Setup base firewalld.conf file
  copy:
    owner=root
    group=root
    mode=600
    src=firewalld.conf
    dest=/etc/firewalld/firewalld.conf
  notify: restart firewalld
- name: Delete public zone
  file:
    path=/etc/firewalld/zones/public.xml
    state=absent
  notify: restart firewalld
- name: Setup local zone
  copy:
    owner=root
    group=root
    mode=644
    src=local.xml
    dest=/etc/firewalld/zones/local.xml
  notify: restart firewalld
- name: Setup vboxnat zone
  copy:
    owner=root
    group=root
    mode=644
    src=vboxnat.xml
    dest=/etc/firewalld/zones/vboxnat.xml
  notify: restart firewalld
- name: Enable firewalld
  service:
    name=firewalld
    state=started
    enabled=yes
