---
- name: Install epel-release
  yum:
    name: epel-release
    state: present
- name: Install base packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - vim-enhanced
    - htop
    - rxvt-unicode-256color
    - wget
