---
- name: Install base packages
  yum:
    name={{ item }}
    state=present
  with_items:
    - vim-enhanced
    - wget
    - git
    - nmap-ncat
    - epel-release
    - htop
    - tmux
    - rpm-build
    - rpmdevtools
    - mysql-connector-java
    - MySQL-python
